# Generated by Django 5.2.1 on 2025-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
