# Generated by Django 5.2.1 on 2025-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_borrower_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='amount',
            field=models.FloatField(),
        ),
    ]
