# Generated by Django 5.2.1 on 2025-07-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user_details',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
