# Generated by Django 5.2.1 on 2025-07-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_last_name_user_details_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('defaulted', 'Defaulted')], default='active', max_length=10),
        ),
    ]
